name: reikodev_website
description: A new Flutter project.

publish_to: 'none'

version: 1.0.2

environment:
  sdk: ">=2.18.0-149.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  eva_icons_flutter: ^3.1.0
  google_fonts: ^2.3.1
  url_launcher: ^6.0.20
  get: ^4.6.1
  lottie: ^1.3.0
  auto_size_text: ^3.0.0
  freezed_annotation: ^2.0.1
  json_serializable:
  dartz: ^0.10.1
  go_router: ^3.1.0
  flutter_staggered_grid_view: ^0.6.1
  visibility_detector: ^0.3.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  icons_launcher: ^1.1.8
  
  flutter_lints:
flutter_icons:
    android: true
    ios: true
    web: true
    windows: true
    image_path: "assets/icon/icon.png"  

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/projects/
    - assets/images/profile/
    - assets/images/experiences/
    - assets/videos/
    - assets/lottie/